# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-01 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_categorie_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
