# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-14 10:04
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20160131_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='couleur',
            field=colorfield.fields.ColorField(default=b'#00C0EF', max_length=10),
        ),
        migrations.AddField(
            model_name='item',
            name='couleur',
            field=colorfield.fields.ColorField(default=b'#00C0EF', max_length=10),
        ),
    ]
