# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='promotion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Promotion'),
        ),
        migrations.AddField(
            model_name='historicalclient',
            name='promotion',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='api.Promotion'),
        ),
    ]
