# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20160326_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_la_transaction', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
