# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-27 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.Client'),
            preserve_default=False,
        ),
    ]
